<?php
/**
 * Bearer-token authentication helper used by the Magnitu and export APIs.
 *
 * Seismo 0.5 ships a two-key model:
 *
 *   - `api_key`        — Magnitu sync key. Full read + write access to the
 *                        `magnitu_*` endpoints (entries pull, scores push,
 *                        recipe GET/POST, labels push, status).
 *   - `export:api_key` — Read-only export key. Authorises only the
 *                        `export_briefing` / `export_entries` endpoints.
 *                        A briefing script with this key CANNOT push scores,
 *                        change the recipe, or otherwise mutate state.
 *
 * Keys are stored in `system_config` (renamed from `magnitu_config` in
 * Slice 5a, schema 21); values are opaque random strings generated by
 * the admin.
 *
 * Token is accepted from the standard `Authorization: Bearer …` header,
 * the `HTTP_AUTHORIZATION` / `REDIRECT_HTTP_AUTHORIZATION` SAPI fallbacks
 * (CGI / FastCGI hosts), or as a `?api_key=` / POST `api_key` parameter —
 * matching 0.4's compatibility behaviour so Magnitu's `sync.py` works
 * unchanged against both versions.
 */

declare(strict_types=1);

namespace Seismo\Http;

use Seismo\Repository\SystemConfigRepository;

final class BearerAuth
{
    /**
     * Timing-safe verification against the Magnitu (write) key.
     */
    public static function verifyMagnituKey(SystemConfigRepository $config): bool
    {
        $expected = (string)($config->get('api_key') ?? '');
        return $expected !== '' && hash_equals($expected, self::presentedToken());
    }

    /**
     * Timing-safe verification against the read-only export key.
     *
     * Two-key model defence-in-depth: if the presented token matches the
     * Magnitu write key (`api_key`), refuse regardless of the export key's
     * value. This catches an admin who accidentally generated the same secret
     * for both rows, which would otherwise let a compromised briefing key
     * push scores.
     */
    public static function verifyExportKey(SystemConfigRepository $config): bool
    {
        $presented = self::presentedToken();
        if ($presented === '') {
            return false;
        }
        $magnituKey = (string)($config->get('api_key') ?? '');
        if ($magnituKey !== '' && hash_equals($magnituKey, $presented)) {
            return false;
        }
        $expected = (string)($config->get('export:api_key') ?? '');

        return $expected !== '' && hash_equals($expected, $presented);
    }

    /**
     * Short helper: emit a JSON 401 body and return false so callers can
     * `if (!BearerAuth::guardMagnitu(...)) return;`. Kept here so every
     * endpoint produces the same response shape.
     */
    public static function guardMagnitu(SystemConfigRepository $config): bool
    {
        if (self::verifyMagnituKey($config)) {
            return true;
        }
        self::respondUnauthorized();
        return false;
    }

    public static function guardExport(SystemConfigRepository $config): bool
    {
        if (self::verifyExportKey($config)) {
            return true;
        }
        self::respondUnauthorized();
        return false;
    }

    /**
     * Read the raw presented token. Empty string when none supplied.
     * Never returns null, so callers can safely use hash_equals().
     */
    private static function presentedToken(): string
    {
        $header = '';

        if (function_exists('getallheaders')) {
            $headers = getallheaders();
            if (is_array($headers)) {
                $header = (string)($headers['Authorization'] ?? $headers['authorization'] ?? '');
            }
        }
        if ($header === '' && !empty($_SERVER['HTTP_AUTHORIZATION'])) {
            $header = (string)$_SERVER['HTTP_AUTHORIZATION'];
        }
        if ($header === '' && !empty($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])) {
            $header = (string)$_SERVER['REDIRECT_HTTP_AUTHORIZATION'];
        }

        if ($header !== '' && preg_match('/^Bearer\s+(.+)$/i', $header, $m)) {
            return trim($m[1]);
        }

        // Fallback: query string or POST body (0.4 compatibility).
        $fallback = $_GET['api_key'] ?? $_POST['api_key'] ?? '';
        return is_string($fallback) ? trim($fallback) : '';
    }

    private static function respondUnauthorized(): void
    {
        http_response_code(401);
        header('Content-Type: application/json; charset=utf-8');
        echo json_encode(['error' => 'Invalid API key']);
    }
}
